---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: bar
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: hari0125/nginx:v0.1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"
